#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /downloads \
    /incomplete-downloads

# permissions
chown abc:abc \
    /downloads \
    /incomplete-downloads

find /config -path /config/Downloads -prune -o -exec chown abc:abc {} +
